In [49]:
# Internship at DataX Labs: Day 1
# Author : Lord Davon Mendoza
# Dataset: Customer Personality Analysis
# Task: Data Cleaning and Preprocessing
# Tools: Python, Google Colab


# Loading all the libraries
import pandas as pd

In [ ]:
# Loading the dataset
df = pd.read_csv('marketing_campaign.csv', sep='\t')

In [190]:
# Show a quick table summary
df.head()

Empty DataFrame
Columns: [id, year_birth, education, marital_status, income, kidhome, teenhome, dt_customer, recency, mnt__wines, mnt__fruits, mnt__meatproducts, mnt__fishproducts, mnt__sweetproducts, mnt__goldprods, num__dealspurchases, num__webpurchases, num__catalogpurchases, num__storepurchases, num__webvisitsmonth, acceptedcmp__3, acceptedcmp__4, acceptedcmp__5, acceptedcmp__1, acceptedcmp__2, complain, z_costcontact, z_revenue, response]
Index: []

[0 rows x 29 columns]

In [189]:
# Shows column names, data types, and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     0 non-null      int64
 1   year_birth             0 non-null      int64
 2   education              0 non-null      object
 3   marital_status         0 non-null      object
 4   income                 0 non-null      float64
 5   kidhome                0 non-null      int64
 6   teenhome               0 non-null      int64
 7   dt_customer            0 non-null      datetime64[ns]
 8   recency                0 non-null      int64
 9   mnt__wines             0 non-null      int64
 10  mnt__fruits            0 non-null      int64
 11  mnt__meatproducts      0 non-null      int64
 12  mnt__fishproducts      0 non-null      int64
 13  mnt__sweetproducts     0 non-null      int64
 14  mnt__goldprods         0 non-null      int64
 15  num__dealspurchases    0 non-null      int64
 16  num__webpurchases      0 non-null      int64
 17  num__catalogpurchases  0 non-null      int64
 18  num__storepurchases    0 non-null      int64
 19  num__webvisitsmonth    0 non-null      int64
 20  acceptedcmp__3         0 non-null      int64
 21  acceptedcmp__4         0 non-null      int64
 22  acceptedcmp__5         0 non-null      int64
 23  acceptedcmp__1         0 non-null      int64
 24  acceptedcmp__2         0 non-null      int64
 25  complain               0 non-null      int64
 26  z_costcontact          0 non-null      int64
 27  z_revenue              0 non-null      int64
 28  response               0 non-null      int64
dtypes: datetime64[ns](1), float64(1), int64(25), object(2)
memory usage: 0.0+ bytes

In [195]:
# Check and display summary statistics for numeric columns
df.describe()

,id,year_birth,income,kidhome,teenhome,dt_customer,recency,mnt__wines,mnt__fruits,mnt__meatproducts,...,num__webvisitsmonth,acceptedcmp__3,acceptedcmp__4,acceptedcmp__5,acceptedcmp__1,acceptedcmp__2,complain,z_costcontact,z_revenue,response
count,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [140]:
# Check for missing values in each column
df.isnull().sum()

id                      0
year_birth              0
education               0
marital_status          0
income                  0
kidhome                 0
teenhome                0
dt_customer             0
recency                 0
mnt_wines               0
mnt_fruits              0
mnt_meatproducts        0
mnt_fishproducts        0
mnt_sweetproducts       0
mnt_goldprods           0
num_dealspurchases      0
num_webpurchases        0
num_catalogpurchases    0
num_storepurchases      0
num_webvisitsmonth      0
acceptedcmp_3           0
acceptedcmp_4           0
acceptedcmp_5           0
acceptedcmp_1           0
acceptedcmp_2           0
complain                0
z_costcontact           0
z_revenue               0
response                0
dtype: int64

In [205]:
# Check unique values
for col in df.select_dtypes(include='object').columns:
    print(f"{col}: {df[col].unique()}")

education: []
marital_status: []

In [147]:
# Check value count
for col in df.columns:
    print(f"--- Value Counts for {col} ---")
    print(df[col].value_counts())
    print("\n")

--- Value Counts for id ---
id
9405    1
5524    1
2174    1
4141    1
6182    1
       ..
6565    1
4939    1
9736    1
2114    1
2569    1
Name: count, Length: 2238, dtype: int64


--- Value Counts for year_birth ---
year_birth
1976    89
1971    87
1975    83
1972    79
1978    77
1970    77
1965    74
1973    72
1969    71
1974    69
1956    55
1979    53
1958    53
1977    52
1952    52
1959    51
1968    51
1966    50
1954    50
1955    49
1960    49
1963    45
1982    45
1967    44
1962    44
1957    43
1951    43
1983    42
1986    42
1964    42
1981    39
1980    39
1984    38
1961    36
1953    35
1985    32
1949    30
1989    30
1950    29
1988    29
1987    27
1948    21
1990    18
1946    16
1947    16
1991    15
1992    13
1945     8
1943     7
1944     7
1995     5
1993     5
1994     3
1996     2
1900     1
1893     1
1899     1
1941     1
1940     1
Name: count, dtype: int64


--- Value Counts for education ---
education
Graduation    1127
PhD            484
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64


--- Value Counts for marital_status ---
marital_status
Married     864
Together    580
Single      485
Divorced    309
Name: count, dtype: int64


--- Value Counts for income ---
income
51381.5    24
7500.0     12
35860.0     4
18929.0     3
67445.0     3
           ..
58025.0     1
33562.0     1
57731.0     1
73807.0     1
35893.0     1
Name: count, Length: 1975, dtype: int64


--- Value Counts for kidhome ---
kidhome
0    1291
1     899
2      48
Name: count, dtype: int64


--- Value Counts for teenhome ---
teenhome
0    1158
1    1028
2      52
Name: count, dtype: int64


--- Value Counts for dt_customer ---
dt_customer
2012-08-31    12
2013-02-14    11
2012-09-12    11
2014-05-12    11
2014-05-22    10
              ..
2013-11-01     1
2013-08-10     1
2012-10-11     1
2012-12-20     1
2014-01-09     1
Name: count, Length: 663, dtype: int64


--- Value Counts for recency ---
recency
56    37
54    32
30    32
46    31
92    30
      ..
41    15
59    14
22    13
7     12
44    11
Name: count, Length: 100, dtype: int64


--- Value Counts for mnt_wines ---
mnt_wines
2       42
5       40
6       37
1       37
4       33
        ..
673      1
58       1
879      1
1245     1
426      1
Name: count, Length: 776, dtype: int64


--- Value Counts for mnt_fruits ---
mnt_fruits
0      400
1      162
2      120
3      114
4      104
      ...
131      1
140      1
149      1
143      1
154      1
Name: count, Length: 158, dtype: int64


--- Value Counts for mnt_meatproducts ---
mnt_meatproducts
7      53
5      50
11     49
8      46
6      43
       ..
883     1
450     1
498     1
164     1
182     1
Name: count, Length: 558, dtype: int64


--- Value Counts for mnt_fishproducts ---
mnt_fishproducts
0      384
2      156
3      130
4      106
6       82
      ...
181      1
81       1
128      1
114      1
229      1
Name: count, Length: 182, dtype: int64


--- Value Counts for mnt_sweetproducts ---
mnt_sweetproducts
0      419
1      161
2      128
3       99
4       82
      ...
262      1
179      1
100      1
79       1
111      1
Name: count, Length: 177, dtype: int64


--- Value Counts for mnt_goldprods ---
mnt_goldprods
1      73
4      70
3      69
12     63
5      63
       ..
245     1
229     1
248     1
103     1
247     1
Name: count, Length: 213, dtype: int64


--- Value Counts for num_dealspurchases ---
num_dealspurchases
1     970
2     497
3     297
4     189
5      92
6      61
0      46
7      40
8      14
9       8
15      7
11      5
10      5
12      4
13      3
Name: count, dtype: int64


--- Value Counts for num_webpurchases ---
num_webpurchases
2     373
1     354
3     336
4     280
5     220
6     205
7     153
8     102
9      75
0      49
11     44
10     43
27      2
23      1
25      1
Name: count, dtype: int64


--- Value Counts for num_catalogpurchases ---
num_catalogpurchases
0     586
1     495
2     276
3     184
4     182
5     140
6     128
7      79
8      55
10     48
9      42
11     19
28      3
22      1
Name: count, dtype: int64


--- Value Counts for num_storepurchases ---
num_storepurchases
3     490
4     323
2     223
5     212
6     176
8     149
7     143
10    125
9     106
12    105
13     83
11     81
0      15
1       7
Name: count, dtype: int64


--- Value Counts for num_webvisitsmonth ---
num_webvisitsmonth
7     393
6     340
8     340
5     281
4     218
3     205
2     202
1     153
9      83
0      11
20      3
10      3
14      2
19      2
17      1
13      1
Name: count, dtype: int64


--- Value Counts for acceptedcmp_3 ---
acceptedcmp_3
0    2075
1     163
Name: count, dtype: int64


--- Value Counts for acceptedcmp_4 ---
acceptedcmp_4
0    2071
1     167
Name: count, dtype: int64


--- Value Counts for acceptedcmp_5 ---
acceptedcmp_5
0    2075
1     163
Name: count, dtype: int64


--- Value Counts for acceptedcmp_1 ---
acceptedcmp_1
0    2094
1     144
Name: count, dtype: int64


--- Value Counts for acceptedcmp_2 ---
acceptedcmp_2
0    2208
1      30
Name: count, dtype: int64


--- Value Counts for complain ---
complain
0    2217
1      21
Name: count, dtype: int64


--- Value Counts for z_costcontact ---
z_costcontact
3    2238
Name: count, dtype: int64


--- Value Counts for z_revenue ---
z_revenue
11    2238
Name: count, dtype: int64


--- Value Counts for response ---
response
0    1905
1     333
Name: count, dtype: int64

In [108]:
# Check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [159]:
#Standardize column names
df.columns = df.columns.str.lower().str.replace(' ', '_').str.replace(r'^(mnt|num|acceptedcmp)(.+)$', r'\1_\2', regex=True)

In [180]:
# Check current data types
df.dtypes

id                                int64
year_birth                        int64
education                        object
marital_status                   object
income                          float64
kidhome                           int64
teenhome                          int64
dt_customer              datetime64[ns]
recency                           int64
mnt__wines                        int64
mnt__fruits                       int64
mnt__meatproducts                 int64
mnt__fishproducts                 int64
mnt__sweetproducts                int64
mnt__goldprods                    int64
num__dealspurchases               int64
num__webpurchases                 int64
num__catalogpurchases             int64
num__storepurchases               int64
num__webvisitsmonth               int64
acceptedcmp__3                    int64
acceptedcmp__4                    int64
acceptedcmp__5                    int64
acceptedcmp__1                    int64
acceptedcmp__2                    int64
complain                          int64
z_costcontact                     int64
z_revenue                         int64
response                          int64
dtype: object

In [119]:
# Convert column to a number
df['income'] = pd.to_numeric(df['income'], errors='coerce')
# Replace missing values from 'Income' column with a placeholder
df['income'] = df['income'].fillna(df['income'].median())

In [174]:
# Check outliers in income
print(df[df['income'] > 200000][['id', 'income']])

Empty DataFrame
Columns: [id, income]
Index: []

In [203]:
# Drop any row where income is above the highest limit
df = df[df['income'] <= 200000]
print(f"Remaining rows: {len(df)}")

Remaining rows: 0

In [148]:
# Convert 'dt_customer' data type
df['dt_customer'] = pd.to_datetime(df['dt_customer'], format='%d-%m-%Y')

In [204]:
# Replace/drop unwanted values in 'Marital Status' column
df['marital_status'] = df['marital_status'].replace('Alone', 'Single')
df = df[~df['marital_status'].isin(['YOLO', 'Absurd'])]

In [178]:
# See rows with problematic birth year
print(df[df['year_birth'] < 1930][['id', 'year_birth']])

Empty DataFrame
Columns: [id, year_birth]
Index: []

In [199]:
# Drop rows with unrealistic birth year
df = df[df['year_birth'] >= 1930]
# Confirm they're gone
print(f"Remaining rows: {len(df)}")

Remaining rows: 0

In [206]:
# Drop useless columns
df = df.drop(columns=['z_costcontact', 'z_revenue'])